### ISSUE TITLE
Low railings across the road in Sefton Park

### ISSUE THREAD

**Issue by amcewen** [Liverpool-UK/somebody-should#26]
Just by the Palm House there's a barrier across the road to stop cars driving through.  It's got two gaps for people and bikes to get through, but on one side the barriers either side of the gap are lower than you'd expect.

When you're cycling through at night it's hard to spot them until you're right upon them.  It'd be handy to have some reflective tape on them to make them show up in your bike lights more easily.

You can see the barriers in question in [this Instagram photo](https://www.instagram.com/p/BPa1yM9Fe_h/?taken-by=amcewen_)

**Comment by mdunschen** [comment]
I've put some reflective tape on these obstructions, and would like to resolve #26, but how do I do this with 'nothing' (i.e. no file changes or additions) to commit? DO i not have to be able to type it into a commit message?

**Comment by amcewen** [comment]
I think the problem was that you weren't part of the "Liverpool-UK" organisation on github, so didn't have closing issue privileges.  I've just sent you an invite for it, so if you accept that you should be able to close this now (or give me a shout if you don't want to be added to the org and I'll close it for you :-)

**Comment by amcewen** [comment]
Done, with proof https://twitter.com/mdunschen/status/852249007724392448 :-)
