### ISSUE TITLE
Design some labels to stick on things

### ISSUE THREAD

**Issue by ajlennon** [Liverpool-UK/somebody-should#27]
I took a look at the Dymo framework support and now have the [QRCodifier](https://github.com/DynamicDevices/qrcodifier) rendering labels.

![doesqrcodifier](https://cloud.githubusercontent.com/assets/1537834/23072957/9c806ce0-f52b-11e6-9202-47308ac27804.png)

What do you think should go on these things? How should they look? Interact with the wiki?

**Comment by ajlennon** [comment]
Hmm in fact maybe we could have these Q/R codes go to a node-red endpoint which could tweet "Somebody scanned X" and redirect to the relevant place. Cor.

**Comment by amcewen** [comment]
Are you on the right Somebody-Should repo?  (Not that I'm against labelling random things around the city, that could be a good idea, but am wondering if you're expecting to be in [this somebody-should](https://github.com/DoESLiverpool/somebody-should/issues) instead?)

**Comment by ajlennon** [comment]
Must be a Freudian thing. Apologies all!

**Comment by amcewen** [comment]
And on the city-wide side of things, this could tie in with #16.

**Comment by ajlennon** [comment]
Nice idea
