### ISSUE TITLE
Visualise public transport across the region

### ISSUE THREAD

**Issue by amcewen** [Liverpool-UK/somebody-should#28]
Mapzen have released a [tool to visualise the frequency of public transport in an area](https://mapzen.com/blog/animating-transitland/).  It'd be lovely to create visualisations for Liverpool/Merseyside.

**Comment by davidtweaver** [comment]
I'd be interested in helping out with this

**Comment by amcewen** [comment]
@davidtweaver You don't happen to be attending HiPy's [Robots and Code](http://www.hipy.uk/) this afternoon/evening do you?  I'm planning on having a crack at it then

**Comment by davidtweaver** [comment]
Ah I didn't know about that - where is it? I'm freelancing all afternoon
but am free this evening

**Comment by amcewen** [comment]
It's at the Materials Innovation Factory at Liv Uni, 4-7pm.

**Comment by amcewen** [comment]
Done.  At least as far as I can with the current data available.  Issue #29 raised to see if we can improve the available data.  Write-up and videos are over on the MCQN Ltd blog - [Mapping Public Transport on Merseyside](http://mcqn.com/posts/mapping-public-transport-on-merseyside/)
