### ISSUE TITLE
Check wether co2 extinguisher needs re filling in laser room

### ISSUE THREAD

**Issue by baronessdesigns** [Liverpool-UK/somebody-should#39]
We were cutting acrylic sheets and a small fire happened. We had to use the extinguisher for around half a second to put out the fire. We dont know whether it needs to be re filled or not?

**Comment by willcrobinson** [comment]
Think you might want to open this issue on the DoESLiverpool somebody-should instead (https://github.com/DoESLiverpool/somebody-should) This repo is for Liverpool city improvements 🙂

**Comment by amcewen** [comment]
Well spotted @willcrobinson :grin:
